<h1>AUTHOR: ADITYA KARKI</h1>
<h3>DATE: FEBRUARY 14, 2023</h3>

In [ ]:
# importing required libraries
import numpy as np
import copy

**Question 1: Write the command(s) that will create a 6x4 matrix with random entries. In what range of numbers do the entries lie? Tell how to create a 3x3 matrix with random integer entries between -9 and 9.**

In [ ]:
# using the numpy random module with rand function to create a 2D array with random entries
sample_matrix1= np.random.rand(6, 4)
print(sample_matrix1)

[[0.11826307 0.55219953 0.19395814 0.72141712]
 [0.22475655 0.46061944 0.58362202 0.05577061]
 [0.16069709 0.94196637 0.55102315 0.54843314]
 [0.24131846 0.82228692 0.66713845 0.68615781]
 [0.04931992 0.35526301 0.78415134 0.43196399]
 [0.42063065 0.98018387 0.38042888 0.25108644]]


*From above we see that the elements inside the matrix are all real numbers in range 0 to 1 (1 exclusive). More specifically, the range is [0, 1) according to random.rand documentation.*

In [ ]:
# using the numpy random module with randint function to create a 2D array with random integers
sample_matrix2 = np.random.randint(-9, 9, size=(3,3)) # keeping the range of matrix from -9 to 9
print(sample_matrix2)


[[ 5  2  2]
 [-4 -5 -6]
 [-3  8  1]]


**Question 2: Use at least three pairs of random 4x4 matrices A and B to test the equalities (A+B)<sup>T</sup>= A<sup>T</sup>+B<sup>T</sup> and 
(AB)<sup>T</sup> = A<sup>T</sup>B<sup>T</sup>. Report your conclusions.** 

A helper function for generating a random 4x4 matrix, with integers from in a defined range.

In [ ]:
def formulate_random_matrix(a, b):
  return np.random.randint(a, b, size=(4, 4))

A helper function for checking if two given matrix satisfy: (A+B)<sup>T</sup>= A<sup>T</sup>+B<sup>T</sup>

In [ ]:
def sum_transpose_checker(A, B):
  # finding sum of A and B
  lhs = np.add(A, B).transpose()
  print("LHS sum: ", lhs)
  # finding sum of A^T and B^T
  rhs = np.add(A.transpose(), B.transpose())
  print("RHS sum: ", rhs)
  # checking if (A+B)^T = A^T+B^T
  return np.array_equal(lhs, rhs)

A helper function for checking if two given matrix satisfy: (AB)<sup>T</sup>= A<sup>T</sup> x B<sup>T</sup>

In [ ]:
def product_transpose_checker(A, B):
  # finding product of A and B
  lhs = np.matmul(A, B).transpose()
  print("LHS product: ", lhs)
  # finding product of A transpose and B transpose
  rhs = np.matmul(A.transpose(), B.transpose())
  print("RHS product: ", rhs)
  # checking if (AB)^T = A^T * B^T
  return np.array_equal(lhs, rhs)

 Generate three random matrices in range (0, 10), (-100, 100), and (10, 35).Then, check if they satisfy given mathematical expressions. 

In [ ]:
ranges = [(0, 10), (-100, 100), (10, 35)]
for i in range(3):
  # generating random matrices
  A = formulate_random_matrix(ranges[i][0], ranges[i][1])
  print("A = ", A)
  B = formulate_random_matrix(ranges[i][0], ranges[i][1])
  print("B = ", B)
  # checking if (A+B)^T = A^T+B^T
  if sum_transpose_checker(A, B):
    print("Sum of transposes are equal on both sides for A and B. Example", i + 1, "passes")
  # checking if (AB)^T = A^T * B^T
  if product_transpose_checker(A, B):
    print("Product of transposes are equal on both sides for A_1 and B_1", i + 1, "passes")
  print()

A =  [[9 5 9 7]
 [6 5 9 1]
 [7 7 9 5]
 [1 8 0 9]]
B =  [[2 1 5 5]
 [6 6 3 1]
 [6 4 8 7]
 [4 6 5 0]]
LHS sum:  [[11 12 13  5]
 [ 6 11 11 14]
 [14 12 17  5]
 [12  2 12  9]]
RHS sum:  [[11 12 13  5]
 [ 6 11 11 14]
 [14 12 17  5]
 [12  2 12  9]]
Sum of transposes are equal on both sides for A and B. Example 1 passes
LHS product:  [[130 100 130  86]
 [117  78 115 103]
 [167 122 153  74]
 [113  98 105  13]]
RHS product:  [[ 64 112 141 107]
 [ 90  89 162  85]
 [ 72 135 162 135]
 [ 85  72 149  59]]

A =  [[ 35  17  63  63]
 [ 14 -18 -56  51]
 [ 67  23   4 -87]
 [ 16  40  79 -59]]
B =  [[ 25  46  48  -8]
 [-95  27 -42 -14]
 [ 87  96   3 -19]
 [ 95  47 -49 -95]]
LHS sum:  [[  60  -81  154  111]
 [  63    9  119   87]
 [ 111  -98    7   30]
 [  55   37 -106 -154]]
RHS sum:  [[  60  -81  154  111]
 [  63    9  119   87]
 [ 111  -98    7   30]
 [  55   37 -106 -154]]
Sum of transposes are equal on both sides for A and B. Example 2 passes
LHS product:  [[10726  2033 -8427 -2132]
 [11078 -2821    -2 

*Seeing the trends from taken examples, (A+B)<sup>T</sup>= A<sup>T</sup>+B<sup>T</sup> but (AB)<sup>T</sup>≠: A<sup>T</sup> x B<sup>T</sup>*

**Question 3:**  Let 𝑆 = <table><tr><td>0<td>1<td>0<td>0<td>0<tr><td>0<td>0<td>1<td>0<td>0<tr><td>0<td>0<td>0<td>1<td>0<tr><td>0<td>0<td>0<td>0<td>1<tr><td>0<td>0<td>0<td>0<td>0</table>

Compute S<sup>k</sup> for k = 2,...,6. 

**Report your observation.** 

In [ ]:
# Constructing the matrix
S = np.matrix('0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1; 0 0 0 0 0') 
print(S)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


A helper function to find product of two matrices.

In [ ]:
def find_kth_power(S, current_product_matrix):
  return np.matmul(S, current_product_matrix)

Computing S<sup>K</sup> for k  = 2 to 6.

In [ ]:
current_product_matrix = copy.deepcopy(S)
for k in range(2, 7):
  current_product_matrix = find_kth_power(S, current_product_matrix)
  # print obtained output
  print("When k = ", k , ", S power k is, ")
  print(current_product_matrix)
  print()

When k =  2 , S power k is, 
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]

When k =  3 , S power k is, 
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

When k =  4 , S power k is, 
[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

When k =  5 , S power k is, 
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

When k =  6 , S power k is, 
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



*From the answers above we can see that the rows inside the given 5x5 matrix are shifted up. More specifically, they shift by one row in every unit increase of k value. It's probably because of the last row of S which is all 0's. In every unit increase of k, it adds another rows of 0s at top of the previous first 0th row.* 